### ISSUE TITLE
Generate data loaders throws exception

### ISSUE THREAD

**Issue by BottlecapDave** [BottlecapDave/Bottlecap.Net.GraphQL.Generation#10]
`Task<IDictionary<long, IEnumerable<Foo>>> GetByIdsAsync(IEnumerable<long> Ids);`

Reports

Unhandled Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Bottlecap.Net.GraphQL.Generation.Templates.DataLoaderExtensions..ctor(TypeDefinition typeDefinition) in /app/Bottlecap.Net.GraphQL.Generation/Templates/DataLoaderExtensions.cs:line 14
   at Bottlecap.Net.GraphQL.Generation.Generator.Generate(String targetNamespace) in /app/Bottlecap.Net.GraphQL.Generation/Generator.cs:line 106
   at Bottlecap.Net.GraphQL.Generation.Cli.Program.Generate(Options options) in /app/Bottlecap.Net.GraphQL.Generation.Cli/Program.cs:line 36
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Bottlecap.Net.GraphQL.Generation.Cli.Program.Main(String[] args) in /app/Bottlecap.Net.GraphQL.Generation.Cli/Program.cs:line 15

Class has other Task methods present

**Comment by BottlecapDave** [comment]
This is fixed in v0.5.0
